### ISSUE TITLE
DNS failures wrongly detected as non-retriable

### ISSUE THREAD

**Issue by vlerenc** [gardener/external-dns-management#161] opened 2021-03-25 09:06 UTC
**What happened**:
According to @vpnachev: DNS issues are detected as non-retriable errors. The DNS controller on the other hand does not respect `shoot.tatus.lastOperation.state=Failed` and updates the DNS records after a while, but the shoot will be in failed state as long as somebody manually retry the operation.

**What you expected to happen**:
Retry operation until it finishes or hits a time limit.

**Comment by rfranzke** [comment] 2021-03-25 09:09
The "root cause" of this is that the dns-controller is not implemented via the [extensions library](https://github.com/gardener/gardener/tree/master/extensions) and does not follow all the [extension contracts](https://github.com/gardener/gardener/tree/master/docs/extensions). This means that above mentioned contract must be implemented explicitly. If we had support for the DNS extension API in the extensions library then it would work out-of-the-box.

**Comment by mandelsoft** [comment] 2021-03-25 14:45
The DNS controller not only reconciles shoot infra related DNS entries but all other entries, requested by any cluster payload also. Therefore it makes absolutely no sense
to connect the DNS entry reconcilation with potential shoot reconcilations.

When it can finally can create an entry it is created, this is not a problem. What would it help if it is only created after a manual shoot reconcilation has been triggered.
This would still require a manual shoot reconcilation.
The problem is on the gardener side, because of the classification of this error as hard infra failure, that requires manual interaction.

May be the rate limit problem only just occurs BECAUSE of the reconcilation of failed entries for the shoot infrastructure, and could be avoided if the entry reconcilation of infra entries is bound to the shoot reconcilation. I don't see this so far, but I might be wrong.
This could easily be avoided by deleting a failed infa entry again before giving up an actual shoot reconcilation by the gardener and only recreating it for the next reconcilation.

**Comment by rfranzke** [comment] 2021-03-25 15:00
Hm, I don't agree with most of the points :-( 

> Therefore it makes absolutely no sense to connect the DNS entry reconcilation with potential shoot reconcilations.

I don't understand why the DNS extension contract should be different compared to all other extension contracts. Yes, the controller can be used independently of Gardener, but it is also the "default" DNS extension for Gardener, so it should follow the contracts.

> The problem is on the gardener side, because of the classification of this error as hard infra failure, that requires manual interaction.

It was a conscious decision after experiences with infrastructure accounts hosting hundreds of clusters. Earlier, we didn't stop the auto-retried reconciliation when we hit API quota limits. This led to situations in which the limit was not recoverable, simply because too many clusters were run in this account. Manual ops-effort was required, i.e., manually stopping the reconciliation (setting the shoot status to `Failed`), and only this helped to let the limits recover.

> May be the rate limit problem only just occurs BECAUSE of the reconcilation of failed entries for the shoot infrastructure, and could be avoided if the entry reconcilation of infra entries is bound to the shoot reconcilation.

Maybe, but generally, this is what the extension contract dictates. The "sovereignty" about when a reconciliation should happen is still with the gardenlet. This allows us to centrally implement control behaviour, e.g., "reconciliations only in the maintenance time window". The DNS controller does not adhere to this contract which is also the reason why it doesn't stop when the shoot is "failed".

Anyways, personally, I don't consider it too critical (DNS is important, yes, but also usually "static" during the lifetime of a cluster). Still, I never was a fan of the fact that the DNS extension is special in many ways. Practically, it obviously has little impact (at the moment, at least), however, from a higher-level "project setup" point of view it seems to be inefficient to maintain such things (like the extension contracts) in multiple ways (assuming you would implement it then you cannot benefit from the default library but have to "duplicate" this logic in your code explicitly).

**Comment by MartinWeindel** [comment] 2021-05-20 08:37
closed as transferred to gardener/gardener

**Closed by MartinWeindel** 2021-05-20 08:37 UTC
